version: "3.9"

services:
  movies-app:
    container_name: movies-app
    image: movies-app/front-end:0.1
    build:
      context: .
      dockerfile: .DockerFile
    logging:
      driver: json-file
    volumes:
      - ./src:/movies-app/src
    ports:
      - 5173:3000
