version: '3.9'
services:
  service-inventory:
    image: movies-app
    build: ./
    container_name: movies
    ports:
      - "1515:3000"
    volumes:
      - ./dist
      - ./node_modules
    movies: 
        build: ./movies
        container_name: movies_app
        ports: 
           - "1515:3000"
        volumes:
            - ./movies:/app
            - ./app/node_modules
